---
### MCToDisc Config ###
# Weebhook here
# For Example
# weebhook: 753557515396055090/sLFE9Z_Hm-ekyZ5eMphYj8HKDOJnz_9bO24zJYWxWcYanbhAmhvxitdGfTVYfRPIg2j8
# you don't need the "https://discordapp.com/api/webhooks/" part
weebhook: 753557515396055090/sLFE9Z_Hm-ekyZ5eMphYj8HKDOJnz_9bO24zJYWxWcYanbhAmhvxitdGfTVYfRPIg2j8